name: music_app
description: A beautiful local music player for Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # Audio playback - most stable packages
  just_audio: ^0.9.35
  audio_session: ^0.1.16

  # Metadata extraction for album art
  audiotags: ^1.4.5
  
  # File system access - latest stable versions
  permission_handler: ^11.0.1
  path_provider: ^2.1.1

  # Caching and performance
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  change_app_package_name: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # App icon generator
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
